Quality gates (#38)
add-quality-gates

diff --git a/.github/workflows/build-test-report.yml b/.github/workflows/build-test-report.yml
--- a/.github/workflows/build-test-report.yml
+++ b/.github/workflows/build-test-report.yml
@@ -56,7 +56,6 @@ jobs:
 
       - name: Compile project (download dependencies and Lombok)
         run: ./mvnw clean compile -DskipTests -Pcompile-lombok
-        continue-on-error: true
 
       - name: Set up services
         run: cd infra/docker_compose && bash restart_docker.sh && cd ../..
@@ -124,34 +123,20 @@ jobs:
 
           echo "=== RUNNING TESTS ==="
           ./mvnw test -P run-superuser-test -q
+          TEST_RESULT=$?
+          if [ $TEST_RESULT -ne 0 ]; then
+          echo "❌ Superuser tests failed with exit code $TEST_RESULT"
+          exit 1
+          fi          
 
       - name: Run API tests
         run: ./mvnw test -P api
-        continue-on-error: true
 
       - name: Run UI tests
         env:
           SERVERUI: http://teamcity-server:8111
           UIREMOTE: http://localhost:4444/wd/hub
         run: |
-          echo "=== CHECK SERVICES BEFORE TESTS ==="
-          echo "TeamCity:"
-          if ! curl -s -f http://localhost:8111/mnt > /dev/null 2>&1; then
-            echo "❌ TeamCity not reachable!"
-            exit 1
-          else
-            echo "✅ TeamCity is reachable"
-          fi
-
-          echo "Selenoid:"
-          if ! curl -s -f http://localhost:4444/wd/hub/status > /dev/null 2>&1; then
-            echo "❌ Selenoid not reachable!"
-            exit 1
-          else
-            echo "✅ Selenoid is reachable"
-          fi
-
-          echo
           echo "=== TEST CONFIG ==="
           echo "SERVER = $SERVER"
           echo "UIREMOTE = $UIREMOTE"
@@ -159,7 +144,6 @@ jobs:
 
           echo "=== RUNNING TESTS ==="
           ./mvnw test -P ui -q
-        continue-on-error: true
 
       # =============== Отчеты: Allure report, Swagger coverage  ===============
       - name: Run Swagger coverage
@@ -167,7 +151,6 @@ jobs:
         run: |
           curl -s http://localhost:8111/app/rest/swagger.json -o teamcity-swagger.json
           chmod +x .swagger-coverage-commandline/bin/swagger-coverage-commandline
-          
           .swagger-coverage-commandline/bin/swagger-coverage-commandline \
             -s teamcity-swagger.json \
             -i target/swagger-coverage-output
