add-quality-gates

diff --git a/.github/workflows/build-test-report.yml b/.github/workflows/build-test-report.yml
--- a/.github/workflows/build-test-report.yml
+++ b/.github/workflows/build-test-report.yml
@@ -56,7 +56,6 @@ jobs:
 
       - name: Compile project (download dependencies and Lombok)
         run: ./mvnw clean compile -DskipTests -Pcompile-lombok
-        continue-on-error: true
 
       - name: Set up services
         run: cd infra/docker_compose && bash restart_docker.sh && cd ../..
@@ -124,10 +123,14 @@ jobs:
 
           echo "=== RUNNING TESTS ==="
           ./mvnw test -P run-superuser-test -q
+          TEST_RESULT=$?
+          if [ $TEST_RESULT -ne 0 ]; then
+          echo "❌ Superuser tests failed with exit code $TEST_RESULT"
+          exit 1
+          fi          
 
       - name: Run API tests
         run: ./mvnw test -P api
-        continue-on-error: true
 
       - name: Run UI tests
         env:
@@ -159,7 +162,6 @@ jobs:
 
           echo "=== RUNNING TESTS ==="
           ./mvnw test -P ui -q
-        continue-on-error: true
 
       # =============== Отчеты: Allure report, Swagger coverage  ===============
       - name: Run Swagger coverage
